### ISSUE TITLE
Command in Section 4.2 raises Error

### ISSUE THREAD

**Issue by BaiYeBuTingXuan** [Haian-Jin/Neural_Gaffer#9]
## Problem Description

When I run the following commands:

```bash
cd neural_gaffer_3d_relighting && export PYTHONPATH=. 

to_train=helmet && python train.py --config configs/gaffer3d_tensorf.txt --basedir ./3d_logs/tensorf/log_${to_train} --datadir ../prepocessed_3d_relighting_data/val_unseen_relighting_only/${to_train}
```

I encounter the following error:

```
Traceback (most recent call last):
  File "~/Neural_Gaffer/neural_gaffer_3d_relighting/train.py", line 5, in <module>
    from renderer import *
  File "~/Neural_Gaffer/neural_gaffer_3d_relighting/renderer.py", line 4, in <module>
    from models.tensoRF import TensorVM, TensorCP, raw2alpha, TensorVMSplit, AlphaGridMask
ModuleNotFoundError: No module named 'models'
```
This error indicates that Python cannot find the models module. This might be due to the way PYTHONPATH is set up or the structure of the project.

**Comment by Haian-Jin** [comment]
Thanks for your finding!
This issue was caused by the reason mentioned in #10 . I didn't encounter this issue when testing locally because I didn't notice the missing file problem caused by the wrong .gitignore.
